sudo: required
language: php
services:
- docker
script:
- docker build --no-cache --pull -t quay.io/wisvch/website:$TRAVIS_BUILD_NUMBER .
after_success:
- if [ "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" == "master" ]; then
    docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io;
    docker push quay.io/wisvch/website:$TRAVIS_BUILD_NUMBER;
  fi
notifications:
  email: false
  slack:
    rooms:
      secure: AOnXrgBKLeOGyNrJbY40Uv2gXtxhz45OmJBSBOPOYFPUzYQBxCrq1SZS/kS/gEltfhKOXU1r+ILxjsDHLSMiYI4byiwgGhK6Vdx/magXUG51fFQCZ+aCqA9Yxsrs/1gJwhfB3kFnzsGC/RvftTnsk8c+MnIDk7nOt/m7zJt3XcxlFxNnMiy3G71CJXBXJGrF9dEXMfXADi9F3/Tez7cqb0XDJwVA1kkcine899PhN29UXO54W0wDXcngxAD/qzNJjZSgS6YmWGJUS2udigLlQr4JD5pFMrYLCNAjaeSwcMD4JmcshTZx+eZuwteKPtmNvvyqCV1o5bP73hkGA1OrfAn59x1M5drEfIjKO+71lFuMTaUleiVR/hnSd9kawQEfQTxTw5Xm2kuMrK6zA7DSYIrByReMIROn+evQx3sz/Ui4wqe6WUQENwnd/WXahnuFgMboHUApltlGSGcxD0zxbBEdw/vjpV8S+lf/gm3modt4IphrfkLJhjugoaF8Ja2EuQTf59UOvCYBG+j46BIZyMy3LkMKy3ThF73fLgT/Bdi2nOsPG7NNjcJlPvgwHKgimRT8wr0TXMVG5pRXSOojCEjAjoxn6jli8yv9ujnpIqJbpsk4qFW4j4qlMuRo/EzGHPQQA8O8WH/1IWhTZXTJPZgtEvpxeHSKjISz9wzyuWE=
