version: '3'
services:

  # wordpress
  wordpress:
    build: .
    restart: always
    volumes:
      - www-data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_PREFIX=${WORDPRESS_DB_PREFIX}
      - W3CIE_THEME=${W3CIE_THEME}
      - W3CIE_PLUGINS=${W3CIE_PLUGINS}
    ports:
     - 80:80
      
volumes:
  www-data:
